#!/usr/bin/env python

import sys
import os
from dateutil import parser

def rename(old_name):
    """Prepend date to filename.

    Date in the file is expected to be in the following format: ^Date: <date>.
    """
    with open(old_name) as f:
        for line in f:
            if line.startswith("Date: "):
                the_date = parser.parse(line[6:])
                new_name = "%s-%s" % (the_date.strftime("%Y-%m-%d"), old_name)
                return new_name

def reformat_YAML_matter(filename):
    """Reformat wheat-formatter header to YAML Matter format."""
    # rename the file
    os.rename(filename, filename + ".bak")
    # open new file
    with open(filename, 'w') as fout:
        fout.write("---\n")
        with open(filename + ".bak") as fin:
            # read the header
            header = True
            for line in fin:
                # write the header to the new file
                if line.startswith("Title: "):
                    fout.write("title: %s" % line[7:])
                    fout.write("layout: post\n")
                    fout.write("category: general\n")
                    fout.write("tags: []\n")
                    fout.write("---\n")
                    fout.write("{% include JB/setup %}\n\n")
                # skip header, write the rest of the lines to the file
                if not header:
                    fout.write(line)
                # empty line separates header from the text
                if len(line.strip()) == 0:
                    header = False

if __name__ == "__main__":
    filename = sys.argv[1]
    new_name = rename(filename)
    reformat_YAML_matter(filename)
    print(new_name)
    sys.exit(0)

